[tool.portray.mkdocs.theme]
favicon = "docs/images/logo_small.png"
logo = "docs/images/logo_small.png"
name = "material"
palette = {primary = "blue grey", accent = "red"}

[[tool.portray.mkdocs.nav]]
Home = "README.md"

[[tool.portray.mkdocs.nav]]
Changelog = "CHANGELOG.md"

[[tool.portray.mkdocs.nav]]
    [[tool.portray.mkdocs.nav.Contributing]]
    "1. Contributing Guide" = "docs/contributing/1.-contributing-guide.md"

    [[tool.portray.mkdocs.nav.Contributing]]
    "2. Coding Standard" = "docs/contributing/2.-coding-standard.md"

    [[tool.portray.mkdocs.nav.Contributing]]
    "3. Code of Conduct" = "docs/contributing/3.-code-of-conduct.md"

    [[tool.portray.mkdocs.nav.Contributing]]
    "4. Acknowledgements" = "docs/contributing/4.-acknowledgements.md"

[[tool.portray.mkdocs.nav]]
    [[tool.portray.mkdocs.nav."Quick Start"]]
    "1. Installation" = "docs/quick_start/1.-installation.md"

    [[tool.portray.mkdocs.nav."Quick Start"]]
    "2. CLI" = "docs/quick_start/2.-cli.md"

    [[tool.portray.mkdocs.nav."Quick Start"]]
    "3. API" = "docs/quick_start/3.-api.md"

    [[tool.portray.mkdocs.nav."Quick Start"]]
    "4. Configuration" = "docs/quick_start/4.-configuration.md"
