settings:
  target_processing_fps: 2.0
  cpu_pressure_threshold: 85.0

notifications:
  telegram:
    bot_token: "123456:ABC"  # Replace with your bot token
    chat_id: "123456789"     # Replace with your chat/channel id
    timeout: 10
    max_workers: 2
    enable_commands: true    # Allow Telegram add_poi workflow
    command_poll_timeout: 20 # Seconds to wait for new messages when polling

logging:
  level: INFO
  file: face_recognition.log

plates:
  enabled: false
  watchlist: []
  alert_on_watchlist: true
  alert_on_every_plate: false
  capture_cooldown: 30
  storage:
    base_dir: captures/plates
    summary_file: plates_summary.json
    max_captures_per_plate: 20
  ocr:
    languages:
      - en
    use_gpu: false
