settings:
  target_processing_fps: 2.0
  cpu_pressure_threshold: 85.0

notifications:
  telegram:
    bot_token: "123456:ABC"  # Replace with your bot token
    chat_id: "123456789"     # Replace with your chat/channel id
    timeout: 10
    max_workers: 2
