cameras:
  - name: "Name for this camera"
    stream_url: "Complete URL"
    headers:
      Accept: "*/*"
      Accept-Language: "en,en-US;"
      Connection: "keep-alive"
      DNT: "1"
    process_frame_interval: 30  # Process every 30 frames
    capture_cooldown: 120        # 60 seconds cooldown between captures for the same person

#  - name: "Laptop WebCam" # IN CASE YOU WISH TO TRY OUT THE RECOGNITION LOCALLY
#    stream_url: "0"  # '0' typically refers to the default webcam
#    headers: {}        # No headers needed for local webcams
#    process_frame_interval: 15  # Process every 15 frames
#    capture_cooldown: 120       # 120 seconds cooldown between captures for the same person
